/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MazBtn: typeof import('maz-ui/components/MazBtn')['default']
    MazSelect: typeof import('maz-ui/components/MazSelect')['default']
  }
  export interface ComponentCustomProperties {
    vLazyImg: typeof import('maz-ui')['vLazyImg']
  }
}
