/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MazBtn: typeof import('maz-ui/components/MazBtn')['default']
    MazTabs: typeof import('maz-ui/components/MazTabs')['default']
    MazTabsBar: typeof import('maz-ui/components/MazTabsBar')['default']
    MazTabsContent: typeof import('maz-ui/components/MazTabsContent')['default']
    MazTabsContentItem: typeof import('maz-ui/components/MazTabsContentItem')['default']
  }
}
